import { useState } from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import PopularJSQ from "../components/PopularJSQ";
import Map from "../components/Map";
import Filter from "../components/Filter";
import ForEach from "../components/ForEach";
import Reduce from "../components/Reduce";

export default function Home() {
  const [count, setCount] = useState(1);

  return (
    <div className="p-4">
      <style jsx>{`
        .main {
          min-height: 85vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
      `}</style>
      <Head>
        <title>A very famous Javascript interview question</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        {/* <PopularJSQ title="A very famous Javascript interview question" /> */}
        <Map
          title=".map( ) Method"
          description="Iterates through array, computes, &amp; returns a new array."
        />
        <ForEach
          title=".forEach( ) Method"
          description="Iterates through array, nothing returned."
        />
        <Filter
          title=".filter( ) Method"
          description="IF condition is met result returned in a new array."
        />
        <Reduce
          title=".reduce( ) Method"
          description="Takes into account a previous, current &amp; an accumulator"
        />
      </div>
      <Footer />
    </div>
  );
}
