import { useState } from "react";
import Head from "next/head";
import Footer from "../components/Footer";
import PopularJSQ from "../components/PopularJSQ";
import Map from "../components/Map";
import Filter from "../components/Filter";
import ForEach from "../components/ForEach";
import Reduce from "../components/Reduce";
import Debouncing from "../components/Debouncing";
import UseEffect from "../components/UseEffect";
import UseReduce from "../components/UseReduce";
import UseState from "../components/UseState";
import RenderingLC from "../components/RenderingLC";

export default function Home() {
  const [count, setCount] = useState(1);

  return (
    <div className="p-4">
      <style jsx>{`
        .main {
          min-height: 85vh;
          padding: 4rem 0;
          flex: 1;
          display: flex;
          flex-direction: column;
          justify-content: center;
          align-items: center;
        }
      `}</style>
      <Head>
        <title>Interview | JS &amp; React Guide </title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main">
        <PopularJSQ title="High Order Functions" />
        <Map
          title=".map( ) Method"
          description="Iterates through array, computes, &amp; returns a new array."
        />
        <ForEach
          title=".forEach( ) Method"
          description="Iterates through array, nothing returned."
        />
        <Filter
          title=".filter( ) Method"
          description="IF condition is met result returned in a new array."
        />
        <Reduce
          title=".reduce( ) Method"
          description="Takes into account a previous, current &amp; an accumulator"
        />
        <Debouncing
          title="Debouncing"
          description="Limits the rate at which a funciton is called."
        />
        <UseState
          title="useState"
          description="Our go-to source for state management."
        />
        <UseReduce
          title="useReducer"
          description="useReducer > useState when state is dependent on another state or when it involves multiple sub-values"
        />
        <UseEffect
          title="useEffect"
          description="Allows us to perform side effects-- data fetching, setting up a subscription, and manually changing the DOM in React components are all examples of side effects."
        />
        <RenderingLC title="Rendering Life Cycle" />
      </div>
      <Footer />
    </div>
  );
}
